### ISSUE TITLE
How do I use overlays?

### ISSUE THREAD

**Issue by michaelpj** [divnix/std#117]
Overlays are a standard part of nixpkgs, and in some cases are essential. How do I use them with `std`'s `inputs.nixpkgs`? I can define my own nixpkgs, but that rather defeats the point.

**Comment by GTrunSec** [comment]
I would like to use the `inputs.nixpkgs.appendOverlays [...]`.
https://github.com/GTrunSec/cells-lab/blob/main/nix/nix-linter/packages/default.nix#L6

**Comment by michaelpj** [comment]
I also don't want to re-import nixpkgs, or risk different parts of my project using different nixpkgs, which isn't necessarily safe.

**Comment by GTrunSec** [comment]
https://github.com/divnix/std/pull/66

**Comment by blaggacao** [comment]
The immediate solution is:


```
# pkgs.nix

{ inputs, cell}: inputs.nixpkgs.extend (self:super {})
```

But that would probably also bad for eval of the `std` CLI since it in-scopes a lot of baggage.

Maybe a little saner would be

```
# pkgs.nix

{ inputs, cell}: {
  pkgs = inputs.nixpkgs.extend (self:super {});
}
```

Note that `nixpkgs` != `pkgs`, where `nixpkgs` for the sake of consitency should always be the unaltered "Nix Package Collection" (as explorable by search.nixos.org).

`pkgs`, then is *any* package collection, but isn't any more closely defined.

So while overlays are sometimes handy in certain mental models (and also computationally more efficient), they also sacrifice on referential conciseness.

In the end, this is a balancing act, and since Standard tries to put open a door for newcomer's adoption of Nix, as well, and not _exclusively_ be a productivity framework for nix veterans, that also means (as an invitation): use overlays very carefully.

This argument presumes "fix points (e.g. overlays) are a hard nut for newcomers".

In that latter interpretation, we could also say: sometimes, the more local, the better, even if that means a bit of a performance hit.

Hope this makes sense. Standard won't _encourage_ the use of global overlays as a special concept.

**Comment by blaggacao** [comment]
In general, I'd recommend to as much as possible consider the approach that @GTrunSec exemplified above:
- keeps the referential conciseness of `nixpkgs` across the repo
- adds additional packages in a way they can align with the rest if `nixpkgs`, but still be "distinct".
- only incurs in one mem-eval-spike

**Comment by blaggacao** [comment]
To be documented as part of #115.

**Comment by blaggacao** [comment]
https://divnix.github.io/std/explain/architecture-decision-records/index.html#6-avoid-fix-point-logic-such-as-overlays

With which I may close this issue.

Maybe it makes sense to pin one like-minded one that captures the gist of the reasoning since people would probably recourse with that question to the issue tracker again (before skimming the docs), anyway.

**Comment by michaelpj** [comment]
This attitude doesn't make sense to me. It's fair enough to avoid concepts such as overlays in `std` itself. It's also fine to not like the way `nixpkgs` is designed. But making it hard for me to _use_ `nixpkgs`, given the reality of how it is currently designed, seems like overreach.

I can use `nixpkgs.extend`, but:
- This requires me to import another nixpkgs, wasting evaluation time. That exactly leads to the problem of having 1000 nixpkgs.
- It makes it more confusing for me within my project, because now I have a wrong "decoy" nixpkgs provided by std, and I have to make sure I never use it by accident.

**Comment by blaggacao** [comment]
Hm, I'm not sure what to do, here. It's not really _attitude_, after all but two conflicting arguments:

---

From the ADR:

> Fix points are also clear instances of overloading global context.

(which is hard for local reasoning, which in turn requires built up of global state for reasoning, which is a considerable investment, which is bad for onboarding)

---

Overlays are a prevalent feature of Nixpkgs and people (who are already very familiar with Nixpkgs) like them.

(I don't know if the resource argument really weights in at the same level of importance? Maybe it does and I'm underestimating it's practical impact?)

---

How would you suggest to resolve this?

We could of course introduce `inputs.pkgs` at the framework level, but that would then essentially superseed said ADR. It would mean that we have to explain `overlays` to _all_ target audiences of Standard and how they work (as complicated as they are not only in terms of "how they work", but also in terms of the "confounding effects via the global context" which they exert).

I'm not sure if there is an elegant way to unite this with one of Standard's primary goals (to make Nix code more accessible).

But maybe, I'm not seeing the inocuity of the actual interactions at this point in time, yet?

**Comment by blaggacao** [comment]
I've just been familiarized with the well-known distinction between _essential_ & _accidential_ complexity.

Using overlays, in most cases &mdash; i.e. when you don't need packages versions magically align across a package subset (e.g. `pythonPackages`) &mdash;  is clearly _accidential_ complexity to me.

**Comment by michaelpj** [comment]
I think it's a red herring to talk about how you don't like overlays. Let's leave that to one side. That's an argument for why you would avoid using them yourself, or for changing the way nixpkgs works. But I don't think it's a good argument for the _std framework_ making it hard to use them. They exist, you need them, trying to cover them up doesn't really help things IMO.

I don't have a strong feeling about how to work this into std - I don't know enough about it! Is there a way to hide it so it's there but not in people's faces. Hidden in the "advanced settings"?

**Comment by blaggacao** [comment]
> I don't have a strong feeling about how to work this into std - I don't know enough about it! Is there a way to hide it so it's there but not in people's faces. Hidden in the "advanced settings"?

That can be a route if we can ensure that everybody who uses them absolutely understand the consequences:

I very much doubt that a lot of people have a clear picture of scenarios where their usage represents accidental complexity and in which other usage scenarios, it's essential complexity.

Of course, it is still better to enable users of `std` to make an absolutely conscientious decision, rather than achieving a similar effect through guardrails.

Another aspect that I'd rather shed light on is that Cells represent _boundaries_. At the same time, Cells are the first and foremost code ordering principle of a standardized repository layout. These boundaries break up global context into smaller chunks. I feel that support for overlays should be captured within the context of a Cell and respect it's boundaries. Otherwise, we'd gain a higher order organizing concept and I currently don't have a mental model to accommodate it.

Can you maybe draw up a short story that would accommodate such concept in the underlaying organizing mental model?

**Comment by michaelpj** [comment]
> I feel that support for overlays should be captured within the context of a Cell and respect it's boundaries.

And yet, most of the std projects I've seen have a global nixpkgs!

Perhaps you want to say something like: if you need nixpkgs in your project, define a cell for it and define it however you like. And don't provide a global one.

**Comment by blaggacao** [comment]
> Perhaps you want to say something like: if you need nixpkgs in your project, define a cell for it and define it however you like. And don't provide a global one.

Yes, that _could_ actually work. Just name it `pkgs` or `nixpkgs'` for the additional hint.

And don't declare `inputs.nixpkgs`, so nothing will be autodetected and the special treatment of `inouts.nixpkgs` (because of `legacyPackages`) wouldn't kick in.

It could be called `inputs.pkgs` or `inputs.nixpkgs'`.

**Comment by nrdxp** [comment]
Since we already handle nixpkgs specially, what if we also handled a cell name `nixpkgs` specially, in that it exports a block `pkgs` by default (without having to explicate it in the api), and it is expected to re-export nixpkgs with whatever overlays, patches etc applied.

I see both sides here, using standard really helps cut down the complexity of working with Nix (at least once you get the hang of it), like no other project I've used in the community specifically _because_ it cuts down on the complexity added by the fixed-point centric apporach everywhere else, but

There is a lot of community effort already poured into overlays, and something things that may only be consumable via overlays because of their prevalence, so we should have at least some clear pathway for managing them.

**Comment by blaggacao** [comment]
> There is a lot of community effort already poured into overlays, and some things that may only be consumable via overlays because of their prevalence, so we should have at least some clear pathway for managing them.

As a first step, I'd prefer a pattern piece (`./docs/patterns`) in the docs (with a big warning about the trade-offs discussed herein). I think that's the right way to approach this. I actually don't really like the special treatment of `nixpkgs`: it's really an impure concession to history. It can only work  because it also concedes to principle (by removing the infamous `legacyPackages` out of plain sight [& it anticipates the idea of a "package only" view into the nixpkgs repository]).

**Comment by nrdxp** [comment]
I just fear if you make this too painful, people simply won't use it. Bearing in mind I actually agree with you about why overlays are bad, but the fact is most people coming onboard will be quite used to them, and not being able to apply them may be frustrating enough to abandon their effort. So long as eveything is properly docmented and a big **don't use overlays unless you have no other choice** warning is made in the appropriate places, I see no reason why we can't be this at least passably simple for the user.

**Comment by blaggacao** [comment]
Checkpoint Summary:
 - Any use of `applyOverlays`, regardless if one notices or not, incurs in the (significant) extra work of an extra evaluation of `nixpkgs`: the fix point is moved. This is true in the same way for when overlays are passed during import of `nixpkgs`: there isn't any special magic which would somehow avoids this extra cost.
- One can trivially obtain a package set with a moved fixed point. For semantic consistency, this cannot be possibly called `inputs.nixpkgs` anymore, since that is a fully qualified name which expectations attached to it.

To create such a package set:

```nix
# cells/toolchain/pkgs.nix
{inputs, cell}: inputs.nixpkgs.applyOverlays [
  (_: _: cell.overlays)
  inputs.foo.oveelays.default
]
# we really, really don't need 'final', do we?
```

```nix
# cells/toolchain/overlays.nix
{inputs, cell}: let
  inherit (inputs) nixpkgs;
in {
  # here: 'inouts.nixpkgs' acts as 'prev'
  shellPackage = nixpkgs.nu;
  # but if we really can't live without 'final', this should work:
  inherit (cell.pkgs) hello;
}
```

This honestly ses to satisfy all mentioned requirements. The final art will be accessible for example like this:

```nix
{inputs, cell}: let
  inherit (inputs.cells.toolchain) pkgs;
in {
}
```

The only caveat is that this renders the TUI unusable. We may need to find a solution for this. Maybe similar to the ci shorthands, we could do `(installables "pkgs" {cli = false;})`

I'd be happy if somebody would want to step out and write a pattern piece on this.
