### ISSUE TITLE
how to set nixpkgs config

### ISSUE THREAD

**Issue by lelongg** [divnix/std#185]
I would like to accept android license by setting nixpkgs config but I cannot find a way to do it properly with std

```nix
config = {
   android_sdk.accept_license = true;
};
```

**Comment by blaggacao** [comment]
Two options:

- `std.grow { nixpkgsConfig = {}; }` - applies to `inputs.nixpkgs`

- for others: `pkgs = inputs.my-other-nixpkgs { config = {}; overlays = []; };`


Only `inputs.nipkgs` is special.

I have to add that if the use case is NixOS, maybe it's wirth to have a look at `divnix/hive`, because `std` as-is isn't really optimized for the NixOS case (yet). So handling different channels (i.e. `my-other-nixpkgs`) is maybe a little less ergonomic that it _could_ be.

**Comment by lelongg** [comment]
Thanks a lot ! By the way, the "grow" part remains the most mysterious to me after reading the book
