### ISSUE TITLE
deprecation warnings are too noisy

### ISSUE THREAD

**Issue by nrdxp** [divnix/std#258]
While its nice to be able to see exactly what action needs to be taken in your own flake, it can be quite annoying to be stuck with a downstream flake that is perpetually deprecated. It can also be hard to track down which flake the warning is coming from.

There are two things I can think might improve this:
* if we could somehow only spit deprecation warnings on the current working flake
* or if we could at least provide the user the exact context of the deprecation and which flake it comes from

**Comment by blaggacao** [comment]
I have thought about this at lenght and couldn't find an answer:

> if we could somehow only spit deprecation warnings on the current working flake

As a consumer of an upstream repository, they are part of a consumer's code path.
Suppose it was possible, and we didn't show them, out of the blue, your code could break (without any warning).

>  if we could at least provide the user the exact context of the deprecation and which flake it comes from

Once we're inside that code-path of the  framework, we only have anonymous values, since we're already past the importer.

We also can't simply add file location, since that would simply reference a version of `std` code which raises the deprecation node, but not the caller.

Short of Nix learning to trace on warnings, I don't know what to do about this.

**Comment by blaggacao** [comment]
@nrdxp Could this help? https://nixos.org/manual/nix/stable/language/builtins.html#builtins-traceVerbose

**Comment by blaggacao** [comment]
@nrdxp Can you try with https://github.com/divnix/paisano/pull/4

atop: https://github.com/divnix/std/pull/195

**Comment by blaggacao** [comment]
One reason this has become even more verbose recently is [unscoping `init` from system](https://github.com/divnix/std/commit/2d3ee4b663ccd7627d0f18a680239f7ffaad83c8#diff-e0d0525688b30ecf48f2ddb93dbfe886a2fd77852ae67fb640892138d4c398e2R409). It eagerly evaluates more than the current system just to drop the effort later via `uniqe`. That was possible because `init`'s output doesn't depend on `system` at all, but it's evaluation path, unfortunately, does (namely via an eager evaluation of `drv` to fetch `meta.description`).

When working on the registry schema, I had a strong urge to make it semantically right (non-system scoped) but didn't consider at that time the evaluation overhead (and this issue's way of manifesting).

Reverting now on paisano / #195.

`traceVerabose`, btw is relatively handy, however, since evaluation is lazy, the order of the printed statements doesn't necessarily correspond to stack scope, which makes them only of very limited use for this issue. I'll experiment some more.
