### ISSUE TITLE
infinite recursion encountered when merging attrs from other organelles

### ISSUE THREAD

**Issue by GTrunSec** [divnix/std#52]
I don't know what the reason is at present, it may be caused by the filterattr process.

- https://github.com/GTrunSec/Coding-Dev-Env-With-NixFlake/blob/main/std/cells/test/lib.nix#L11
  -  merging cell.library.mapAttrs' [infinite recursion encountered]
  -  merging mapAttrs [works]

Reproduce code:

```
git clone https://github.com/GTrunSec/Coding-Dev-Env-With-NixFlake
cd Coding-Dev-Env-With-NixFlake/std
nix eval --json --option warn-dirty false .\#__std.x86_64-linux.test.lib
```

expected output:

```
{"foo_x":{"__std_cell":"test","__std_clade":"functions","__std_description":"n/a","__std_name":"foo_x","__std_organelle":"lib"},"foo_y":{"__std_cell":"test","__std_clade":"functions","__std_description":"n/a","__std_name":"foo_y","__std_organelle":"lib"}}% 
```

**Comment by blaggacao** [comment]
This is a known issue, similar to the flake infinit recursion.

At times, I was able to work around via a let block

```nix
{ inputs, cell}:
let
  out = thing.causing.inifint.recurtion;
in { inherit (out) all the attrs you want but manually declared; }
```

since this pattern is not really nice to maintain, I figured that by teaching nix to _not_ evaluate anything left of the `=` it works, like in: https://github.com/divnix/hive/blob/9b8c1fa81ee69a449368eea38b1d29c2ca83b5b6/comb/blaggacao/homeConfigurations.nix#L17

Works:
```nix
let
in
  builtins.mapAttrs (_QUEEN.library.bearHomeConfiguration home) {
    blaggacao = {
      imports = shell;
      programs.browserpass.enable = true;
      programs.git = {
        userName = name;
        userEmail = email;
        signing = {
          key = gitSigningKey;
          signByDefault = true;
        };
      };
    };
 ```
I don't remember exactly the case in which it wouldn't work, but similar as in your case, it involved some calculus on the left hand side of a `=` assignment (`mapAttrs'`).

**Comment by blaggacao** [comment]
This issue doesn't appear to be specific of `std` or something that we could solve here. Going to close. Please reopen, if you can narrow it down to something that `std` could plausibly tackle.
